namespace: middleware_automation
name: infinispan
version: "0.1.9"
readme: README.md
authors:
  - Romain Pelisse <rpelisse@redhat.com>
  - Matthew Fernandez <matferna@redhat.com>
  - Guido Grazioli <ggraziol@redhat.com>
description: Install and configure an Infinispan or DataGrid service.
license_file: "LICENSE"
tags:
  - infinispan
  - datagrid
  - redhat
  - rhel
  - rhn
  - server
  - database
  - infrastructure
dependencies:
  "middleware_automation.redhat_csp_download": ">=1.2.1"
repository: https://github.com/ansible-middleware/infinispan
documentation: https://github.com/ansible-middleware/infinispan
homepage: https://github.com/ansible-middleware/infinispan
issues: https://github.com/ansible-middleware/infinispan/issues
