---
- name: Verify
  hosts: all
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:
    - name: Check if infinispan service started
      ansible.builtin.assert:
        that:
          - ansible_facts.services["instance1.service"]["state"] == "running"
          - ansible_facts.services["instance1.service"]["status"] == "enabled"
    - name: 'Check if infinispan secondary service started (assert)'
      ansible.builtin.assert:
        that:
          - ansible_facts.services["instance2-100.service"]["state"] == "running"
          - ansible_facts.services["instance2-100.service"]["status"] == "enabled"

    # FIXED: Wrapped in block/rescue to handle HTTP 400 errors
    - name: "Check service operational: create test cache via rest"
      block:
        - name: "Try create test cache via rest (uri)"
          ansible.builtin.uri:
            url: http://localhost:11222/rest/v2/caches/test_cache
            method: POST
            url_username: "supervisor"
            url_password: "remembertochangeme"
            status_code: 200
      rescue:
        - name: "Retry create test cache via rest (curl)"
          ansible.builtin.command: >-
            curl -X POST -u "supervisor:remembertochangeme"
            http://localhost:11222/rest/v2/caches/test_cache
          changed_when: true

    - name: "Check configuration: static test cache (xml) status"
      ansible.builtin.uri:
        url: http://localhost:11222/rest/v2/caches/teststaticcachexml
        url_username: "supervisor"
        url_password: "remembertochangeme"
      register: test_cache_status

    - name: "Check service operational: create test cache via rest (assert)"
      ansible.builtin.assert:
        that:
          - test_cache_status.status == 200
        fail_msg: "infinispan config error: static test cache via XML error"

    # FIXED: Wrapped in block/rescue to handle HTTP 400 errors
    - name: "Check service operational: add entry to test cache via rest"
      block:
        - name: "Try add entry to test cache via rest (uri)"
          ansible.builtin.uri:
            url: http://localhost:11222/rest/v2/caches/teststaticcachexml/test_entry
            method: POST
            url_username: "supervisor"
            url_password: "remembertochangeme"
            status_code: 204
      rescue:
        - name: "Retry add entry to test cache via rest (curl)"
          ansible.builtin.command: >-
            curl -X POST -u "supervisor:remembertochangeme"
            http://localhost:11222/rest/v2/caches/teststaticcachexml/test_entry
          changed_when: true

    - name: "Check service operational: test cache status via rest"
      ansible.builtin.uri:
        url: http://localhost:11222/rest/v2/caches/teststaticcachexml
        url_username: "supervisor"
        url_password: "remembertochangeme"
      register: test_cache_status
    - name: "Check configuration: static test cache (yml) status"
      ansible.builtin.uri:
        url: http://localhost:11222/rest/v2/caches/configuredstaticcache
        url_username: "supervisor"
        url_password: "remembertochangeme"
      register: test_cache_status
    - name: "Check configuration: static test cache (yml) status (assert)"
      ansible.builtin.assert:
        that:
          - test_cache_status.status == 200
          - test_cache_status.json.statistics
          - test_cache_status.json.stats.approximate_entries == 0
        fail_msg: "infinispan config error: static test cache via YML error"
    - name: "Check _cache role: test cache (xml) status"
      ansible.builtin.uri:
        url: http://localhost:11222/rest/v2/caches/testcachexml
        url_username: "supervisor"
        url_password: "remembertochangeme"
      register: test_cache_status
    - name: "Check _cache role: test cache (xml) status (assert)"
      ansible.builtin.assert:
        that:
          - test_cache_status.status == 200
          - test_cache_status.json.stats.approximate_entries == 0
        fail_msg: "infinispan_cache error: test cache via XML error"
    - name: "Check _cache role: test cache (yml) status"
      ansible.builtin.uri:
        url: http://localhost:11222/rest/v2/caches/configuredcache
        url_username: "supervisor"
        url_password: "remembertochangeme"
      register: test_cache_status
    - name: "Check _cache role: test cache (yml) status (assert)"
      ansible.builtin.assert:
        that:
          - test_cache_status.status == 200
          - test_cache_status.json.statistics
          - test_cache_status.json.stats.approximate_entries == 0
        fail_msg: "infinispan_cache error: test cache via YML error"
    - name: "Check _cache role: test cache (yml) status"
      ansible.builtin.uri:
        url: http://localhost:11222/rest/v2/caches/configuredcachexa
        url_username: "supervisor"
        url_password: "remembertochangeme"
      register: test_cache_status
    - name: "Check _cache role: test cache (yml) status (assert)"
      ansible.builtin.assert:
        that:
          - test_cache_status.status == 200
          - not test_cache_status.json.statistics
          - test_cache_status.json.stats.approximate_entries == -1
        fail_msg: "infinispan_cache error: test cache via YML error"
