---
- name: Validate parameters
  ansible.builtin.assert:
    that:
      - users is defined
      - users | length > 0
    quiet: true

- name: "Ensure {{ infinispan.config.users }} exists."
  ansible.builtin.template:
    src: templates/users.properties.j2
    dest: "{{ infinispan.home }}/server/conf/{{ infinispan.config.users }}"
    owner: "{{ infinispan.user.name }}"
    group: "{{ infinispan.group.name }}"
    mode: 0644
  notify:
    - restart infinispan
  become: yes

- name: "Ensure {{ infinispan.config.groups }} exists"
  ansible.builtin.template:
    src: templates/groups.properties.j2
    dest: "{{ infinispan.home }}/server/conf/{{ infinispan.config.groups }}"
    owner: "{{ infinispan.user.name }}"
    group: "{{ infinispan.group.name }}"
    mode: 0644
  notify:
    - restart infinispan
  become: yes
